### PR TITLE
Serialize polyhedra value

### PR DESCRIPTION
**Pull request by skcho**
Hello Gagan,

I wrote some missing serialization functions. In our analyzer, the analysis results are shared by the serialization.

Since I am not familiar with internal data structures of Elina, please let me know if there are some strange code.

Thank you.
Sungkeun

### CODE REVIEW

**Comment by GgnDpSngh** [comment]
Hi Sungkeun,

Thanks for adding support for serialize and deserialize operations for ELINA. I went through it (without running) and it seems fine to me. You may want to handle the case when the input polyhedron can be bottom separately as "Poly" array will be NULL in that case (Maybe you already handle the case when the input is bottom separately in your analysis).

Cheers,
Gagan

**Comment by skcho** [comment]
Hello Gagan,

> You may want to handle the case when the input polyhedron can be bottom separately as "Poly" array will be NULL in that case (Maybe you already handle the case when the input is bottom separately in your analysis).

Thank you for the review. Oh, I didn't know that and we don't handle that case specifically in our analysis, so we should handle the case in the serialization functions.

Could you point where I should handle the NULL value in the diff? There are three serialization functions on `opt_pk`:

* https://github.com/eth-sri/ELINA/pull/32/files#diff-5e158a433c3fdf13ee856641b71c1136R1314
`opt_pk_serialize_common` for `opt_pk_t* oak`

* https://github.com/eth-sri/ELINA/pull/32/files#diff-5e158a433c3fdf13ee856641b71c1136R1402
`opt_pk_ptr_serialize_common` for `opt_pk_t** poly`

* https://github.com/eth-sri/ELINA/pull/32/files#diff-5e158a433c3fdf13ee856641b71c1136R1410
`opt_pk_array_serialize_common` for `opt_pk_array_t* oa` 

Sincerely,
Sungkeun

**Comment by skcho** [comment]
Well, I think it's about `opt_pk_array_t* oa`: when `oa->is_bottom` is true, `oa->poly` and `oa->acl` are NULL. Is that right?

Sincerely,
Sungkeun

**Comment by GgnDpSngh** [comment]
Hi Sungkeun,

Yes, that is right. The code looks fine now and I am merging the request.

Cheers,
Gagan

**Pull request merged**
